(() => {
  const exact = new Map(Object.entries({
    "讯来有迹，文止于栖。": "What arrives leaves a trace; what is kept finds its roost.",
    "栖": "Qi",
    "关于": "About",
    "如何复制链接": "How to copy a link",
    "微信监听中": "WeChat listening",
    "自动识别公众号与视频号，无需预先选择来源": "Auto-detects Official Account and Channels links—no source setup needed",
    "发现微信分享链接，正在自动分类…": "WeChat share link found; classifying automatically…",
    "微信分享链接已进入捕获任务": "WeChat share link added to the capture queue",
    "捕获任务": "Capture Queue",
    "收起任务列表": "Collapse capture queue",
    "展开任务列表": "Expand capture queue",
    "搜索公众号、视频号或标题": "Search tasks",
    "使用下方标签筛选": "Filter with the tabs below",
    "任务类型": "Task type",
    "全部": "All",
    "公众号": "Articles",
    "视频号": "Videos",
    "清空已完成缓存": "Clear completed cache",
    "内容留在本地 · A QIDU Utility": "Content stays local · A QIDU Utility",
    "示例科技周报": "Demo Tech Weekly",
    "影像测试频道": "Demo Video Channel",
    "城市观察实验室": "Urban Watch Lab",
    "公开文章测试源": "Public Article Demo",
    "公开影像测试源": "Public Video Demo",
    "测试文档：本地内容整理工作流": "Test Article: Local Content Workflow",
    "测试文档：三步完成文章导出": "Test Article: Export in Three Steps",
    "测试文档：正在读取的公开内容": "Test Article: Reading Public Content",
    "测试文档：已完成的归档示例": "Test Article: Completed Archive",
    "测试文档：等待处理的文章": "Test Article: Waiting to Process",
    "测试文档：批量导出示例": "Test Article: Batch Export Demo",
    "测试文档：自动收取与分类演示": "Test Article: Automatic Intake and Classification",
    "测试视频：公开直链识别演示": "Test Video: Public Direct-Link Detection",
    "测试视频：下载进度演示": "Test Video: Download Progress",
    "测试视频：页面识别演示": "Test Video: Page Detection",
    "测试视频：无公开直链示例": "Test Video: No Public Direct Link",
    "测试视频：可下载内容示例": "Test Video: Downloadable Content",
    "测试视频：已完成任务示例": "Test Video: Completed Task",
    "测试视频：自动收取与分类演示": "Test Video: Automatic Intake and Classification",
    "可导出": "Ready to export",
    "可下载": "Downloadable",
    "视频可下载": "Video downloadable",
    "正在读取": "Reading",
    "正在识别": "Detecting",
    "下载中": "Downloading",
    "已完成": "Completed",
    "处理完成": "Completed",
    "失败": "Failed",
    "等待处理": "Waiting",
    "需查看": "Review needed",
    "内容读取完成": "Content ready",
    "内容读取完成，可导出": "Content ready to export",
    "识别到 1 个可下载的公开视频": "Found 1 downloadable public video",
    "正在读取公开文章正文…": "Reading the public article…",
    "正在检查页面中的公开视频…": "Checking the page for public video…",
    "正在下载公开视频…": "Downloading public video…",
    "页面没有公开直接视频地址": "No public direct video URL is available",
    "文章已导出到本地": "Article exported locally",
    "视频已下载到本地": "Video downloaded locally",
    "等待读取公开内容": "Waiting to read public content",
    "这是一份由讯栖项目生成的公开测试文档。": "This is a public test document generated by the XunQi project.",
    "文中的名称、标题和链接均为虚构内容，只用于演示任务识别、预览和导出流程。": "All names, titles, and links are fictional and are used only to demonstrate intake, preview, and export.",
    "你可以勾选多篇测试文章，批量导出为 PDF，也可以选择 Markdown 和本地图片。": "Select multiple test articles for batch PDF export, or choose Markdown with local images.",
    "所有操作都需要用户明确选择，讯栖不会在后台自动下载或完整备份。": "Every action requires an explicit choice. XunQi does not auto-download or create full backups in the background.",
    "类型": "Type",
    "公众号文章": "Official Account article",
    "视频号内容": "Channels video",
    "来源": "Source",
    "分享链接": "Share link",
    "识别结果": "Detection result",
    "1 个可下载视频": "1 downloadable video",
    "0 个可下载视频": "No downloadable videos",
    "作者": "Author",
    "原文链接": "Source link",
    "字数统计": "Character count",
    "资源统计": "Assets",
    "PDF（保留原文结构）": "PDF (preserve original layout)",
    "Markdown + 本地图片": "Markdown + local images",
    "导出原版 PDF": "Export original-layout PDF",
    "导出到本地": "Export locally",
    "打开微信原文": "Open in WeChat",
    "公开视频直链": "Public video link",
    "公开文章": "Public article",
    "重新识别": "Detect again",
    "正在处理": "Processing",
    "下载到本地": "Download locally",
    "下载": "Download",
    "公开视频": "Public video",
    "只下载页面公开声明的 HTTPS 视频文件。": "Only HTTPS video files publicly declared by the page are downloaded.",
    "页面未公开视频地址": "No public video URL",
    "公开页面没有提供视频直链；如需继续，必须由用户明确授权临时嗅探，并在结束后恢复网络。": "The public page provides no direct video link. Continuing requires explicit authorization for temporary detection, followed by network restoration.",
    "这次没有处理成功": "This task could not be completed",
    "当前页面需要你确认": "This page needs your confirmation",
    "可改用授权嗅探助手": "Authorized detection assistant available",
    "首次确认后临时启用本地代理和会话证书；建议先关闭 VPN。": "After your first confirmation, a local proxy and session certificate are enabled temporarily. Turn off your VPN first.",
    "授权嗅探下载": "Authorize detection download",
    "嗅探下载": "Detection download",
    "启用授权嗅探助手": "Enable the authorized detection assistant",
    "启用前请先关闭 VPN 或系统代理；关闭后再点下方按钮。": "Turn off any VPN or system proxy before enabling this assistant.",
    "这次操作会临时把系统 HTTP/HTTPS 流量接入本地下载助手，并安装一张仅供本次连续下载使用的证书。系统可能要求一次指纹或管理员认证。": "This temporarily routes HTTP/HTTPS traffic through a local download assistant and installs a session-only certificate. macOS may request Touch ID or administrator approval once.",
    "只在你确认后启动；公开直链下载仍然优先。": "Starts only after your confirmation; public direct links remain the first choice.",
    "启用期间，系统 HTTP/HTTPS 请求会先经过本地助手；它只对预设的微信/腾讯页面进行解析，其他流量只转发、不保存。": "While enabled, HTTP/HTTPS requests pass through the local assistant. It inspects only approved WeChat/Tencent pages; other traffic is forwarded and not stored.",
    "匹配页面的 Cookie 与登录态仅在本机内存中临时经过助手，不显示、不写日志、不落盘、不上传。": "Matching-page cookies and session data pass through local memory only: never displayed, logged, written to disk, or uploaded.",
    "因为会临时信任本地证书，这不是零风险功能；启用期间请暂停网银、密码修改等敏感操作。": "Because a local certificate is trusted temporarily, this is not risk-free. Pause banking and password changes while it is active.",
    "只应用于你有权保存的内容；讯栖不会绕过账号权限或平台访问控制。": "Use only for content you are authorized to save. XunQi does not bypass account permissions or platform access controls.",
    "视频下载完成后会保留授权，后续视频不再重复认证。": "Authorization stays active after a download, so later videos do not require repeated approval.",
    "你点击“结束并恢复网络”或退出讯栖时，才会恢复原代理并移除证书。": "The original proxy and certificate are restored when you choose “End and restore network” or quit XunQi.",
    "VPN 与系统代理必须在启用前关闭；讯栖检测到它们时会直接阻止启动。": "VPNs and system proxies must be off before enabling. XunQi blocks startup when it detects a conflict.",
    "只有首次授权需要重新加载一次视频号子窗口，这是让微信使用新网络会话所必需的。讯栖会按已复制的分享链接自动下载原来那条；无需刷新，也不要转到浏览器扫码。之后连续下载不会再重新加载。": "Only the first authorization reloads the Channels subwindow so WeChat can use the new network session. XunQi keeps the copied share link and downloads the intended video—no refresh or browser QR scan is needed. Later downloads reuse the session.",
    "取消": "Cancel",
    "同意并启用": "Agree and enable",
    "先关闭 VPN": "Turn off VPN first",
    "Cookie 不落盘": "Cookies never touch disk",
    "演示不启动嗅探": "Demo does not start detection",
    "已保存到": "Saved to",
    "在 Finder 中显示": "Show in Finder",
    "原版长页 PDF 已保存": "Original-layout PDF saved",
    "如何复制微信链接": "How to copy a WeChat link",
    "保持讯栖打开，复制后会自动进入左侧任务列表。": "Keep XunQi open. Copied links appear automatically in the capture queue.",
    "打开文章，点击右上角的三个点（有些微信版本显示四个点），再选择：": "Open an article, select the three-dot menu (four dots in some versions), then choose:",
    "复制链接": "Copy link",
    "打开视频，点击分享按钮，在弹出的菜单中选择：": "Open a video, select Share, then choose:",
    "复制成功后不需要粘贴；讯栖检测到微信位于前台时会自动捕获新链接。": "No paste is needed. XunQi captures a new link when WeChat is in the foreground.",
    "知道了": "Got it",
    "栖 · CHAPTER 01": "QI · CHAPTER 01",
    "讯者，消息之所至；栖者，文章之所安。讯栖只接住你主动复制的微信分享链接， 在本地巡视、整理并归栖，由你决定查看、导出或下载。": "Messages arrive; selected content finds a home. XunQi receives only the WeChat share links you copy, then lets you review, organize, export, or download them locally.",
    "主动接收": "Intentional intake",
    "不按名称订阅，不读取聊天记录，只处理你主动复制或粘贴的链接。": "No name-based subscriptions or chat-history access—only links you copy or paste.",
    "本地归栖": "Local by design",
    "任务、文章与导出结果优先留在你的电脑，不提供云端账号和遥测。": "Tasks, articles, and exports stay on your computer—no cloud account or telemetry.",
    "明确授权": "Explicit authorization",
    "敏感辅助流程必须由你确认，结束后恢复网络并清理临时状态。": "Sensitive helper flows require confirmation and restore network settings and temporary state afterward.",
    "明白了": "Done",
    "关闭关于讯栖": "Close About XunQi",
    "关闭提示": "Dismiss notification"
  }));

  const replacements = [
    ["助手来源：", "Helper source: "],
    ["；微信改版后仍可能无法识别。", "; future WeChat changes may still affect detection."],
    ["约 ", "Approx. "],
    [" 字", " characters"],
    ["图片 ", "Images: "],
    [" 张", ""],
    ["查看更多", "Show more"],
    ["收起", "Show less"],
    ["选择", "Select "],
    ["原版 PDF 已保存到 ", "Original-layout PDF saved to "],
    ["文章已导出到 ", "Article exported to "],
    ["讯栖导出/文章.pdf", "XunQi Exports/Article.pdf"],
    ["讯栖导出/文章.md", "XunQi Exports/Article.md"]
  ].sort((a, b) => b[0].length - a[0].length);

  const englishCover = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(`
    <svg xmlns="http://www.w3.org/2000/svg" width="960" height="540" viewBox="0 0 960 540">
      <rect width="960" height="540" rx="36" fill="#f1efff"/>
      <circle cx="860" cy="90" r="170" fill="#fff" opacity=".42"/>
      <circle cx="70" cy="520" r="150" fill="#dfe2ff" opacity=".7"/>
      <rect x="90" y="82" width="270" height="376" rx="28" fill="#fff" stroke="#d9d6f8" stroke-width="4"/>
      <rect x="132" y="126" width="48" height="48" rx="10" fill="#7658ed"/>
      <path d="m144 149 12 12 23-28" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>
      <g fill="#b8b4d8"><rect x="200" y="143" width="116" height="16" rx="8"/><rect x="132" y="218" width="176" height="16" rx="8"/><rect x="132" y="270" width="132" height="16" rx="8"/><rect x="132" y="322" width="190" height="16" rx="8"/></g>
      <text x="425" y="226" fill="#2d2b55" font-family="Arial, sans-serif" font-size="62" font-weight="700">PUBLIC DEMO</text>
      <text x="425" y="286" fill="#6d6988" font-family="Arial, sans-serif" font-size="28">Fictional names, titles, and links</text>
      <text x="425" y="328" fill="#6d6988" font-family="Arial, sans-serif" font-size="28">for product workflow testing only.</text>
      <rect x="425" y="370" width="190" height="48" rx="24" fill="#7658ed"/>
      <text x="520" y="402" text-anchor="middle" fill="#fff" font-family="Arial, sans-serif" font-size="22" font-weight="700">XUNQI DEMO</text>
    </svg>`)} `;

  function translateValue(value) {
    const match = value.match(/^(\s*)([\s\S]*?)(\s*)$/);
    if (!match) return value;
    const [, leading, core, trailing] = match;
    let translated = exact.get(core) ?? core;
    if (translated === core) {
      for (const [from, to] of replacements) translated = translated.split(from).join(to);
    }
    return `${leading}${translated}${trailing}`;
  }

  function translateTree(root) {
    if (root.nodeType === Node.TEXT_NODE) {
      const parent = root.parentElement;
      if (!parent || ["SCRIPT", "STYLE", "NOSCRIPT"].includes(parent.tagName)) return;
      const next = translateValue(root.nodeValue ?? "");
      if (next !== root.nodeValue) root.nodeValue = next;
      return;
    }
    if (!(root instanceof Element) && root !== document) return;
    const element = root instanceof Element ? root : null;
    if (element) {
      for (const attribute of ["aria-label", "placeholder", "title", "alt"]) {
        if (element.hasAttribute(attribute)) {
          const current = element.getAttribute(attribute) ?? "";
          const next = translateValue(current);
          if (next !== current) element.setAttribute(attribute, next);
        }
      }
    }
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    let node;
    while ((node = walker.nextNode())) translateTree(node);
    if (root instanceof Element) {
      for (const child of root.querySelectorAll("[aria-label], [placeholder], [title], [alt]")) translateTree(child);
    }
  }

  function refresh() {
    document.documentElement.lang = "en";
    translateTree(document.body);
    const cover = document.querySelector("img.article-cover");
    if (cover && !cover.dataset.englishCover) {
      cover.dataset.englishCover = "true";
      cover.src = englishCover;
      cover.alt = "Public XunQi demo document cover";
    }
  }

  const observer = new MutationObserver(() => queueMicrotask(refresh));
  observer.observe(document.body, { childList: true, subtree: true, characterData: true, attributes: true });
  refresh();
  window.__xunqiEnglishDemo = { refresh, observer };
})();
